AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  CentralAwsAccountId:
    Description: Central AWS Account ID
    Type: String
    AllowedPattern: (\d{12}|^$)
    ConstraintDescription: must be an AWS account ID
Resources:
  ChildAccountRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ChildAccountRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            AWS: !Ref CentralAwsAccountId
          Action: sts:AssumeRole
      Path: /
      Policies:
      - PolicyName: CfnStackAssumeRole
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action: "*"
            Resource: "*"
Outputs:
  RemoteAccountRole:
    Value: !GetAtt ChildAccountRole.Arn