global:
  marketplace-ami: false
  owner: quickstart-eng@amazon.com
  qsname: quickstart-trek10-serverless-enterprise-cicd
  regions:
    - ap-northeast-1
    - ap-northeast-2
    - ap-south-1
    - ap-southeast-1
    - ap-southeast-2
    - ca-central-1
    - eu-central-1
    - eu-west-1
    - sa-east-1
    - us-east-1
    - us-east-2
    - us-west-1
    - us-west-2
  reporting: true
 
tests:
  quickstart-trek10-serverless-enterprise-cicdt1:
    parameter_input: quickstart-trek10-serverless-enterprise-cicd-example-params1.json
    template_file: quickstart-trek10-serverless-enterprise-cicd-example1.template
  quickstart-trek10-serverless-enterprise-cicdt2:
    parameter_input: quickstart-trek10-serverless-enterprise-cicd-example-params2.json
    template_file: quickstart-trek10-serverless-enterprise-cicd-example2.template
