AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  ChildAccountRoleArn:
    Type: String
  CentralAccountRoleArn:
    Type: String
  BucketTag:
    Type: String
    Default: "who's your daddy"
Resources:
  QuickStartStackMakerLambda:
    Type: AWS::Lambda::Function
    Properties:
      Handler: lambda_function.lambda_handler
      MemorySize: 128
      Role: !Ref CentralAccountRoleArn
      Runtime: python3.6
      Timeout: 300
      Code:
        S3Bucket: jmmccon-super-stack-daddy
        S3Key: functions/packages/CfnStackAssumeRole/lambda.zip
  CrossAccountStack:
    Type: "AWS::CloudFormation::CustomResource"
    Version: '1.0'
    Properties:
      ServiceToken: !GetAtt 'QuickStartStackMakerLambda.Arn'
      RoleArn: !Ref ChildAccountRoleArn
      TemplateURL: https://jmmccon-super-stack-daddy.s3.amazonaws.com/templates/s3bucket.template.yaml
      ParentStackId: !Ref AWS::StackId
      Region: !Ref AWS::Region
      loglevel: "debug"
      CfnParameters:
        BucketTag: !Ref BucketTag
Outputs:
  BucketArn:
    Value: !GetAtt CrossAccountStack.BucketArn
